name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to Vultr via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VULTR_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/lasertek-odoo"

      - name: Restart Odoo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/lasertek-odoo
            docker restart odoo